# Generated by Django 4.1.5 on 2023-02-13 09:07

import core.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_column='first_name', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(db_column='last_name', max_length=50, verbose_name='Last name')),
                ('birthday', models.DateField(blank=True, default=datetime.date.today)),
                ('email', models.EmailField(max_length=254, validators=[core.validators.ValidateEmailDomain('gmail.com', 'yahoo.com', 'test.com')])),
                ('phone', models.CharField(max_length=20, validators=[core.validators.validate_phone_number])),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
