# Generated by Django 4.1.5 on 2023-01-23 10:44

from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, validators=[core.validators.validate_phone_number]),
        ),
    ]
