# Generated by Django 4.1.5 on 2023-01-22 10:10

from django.db import migrations, models
import groups.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(validators=[groups.validators.validate_start_date]),
        ),
    ]
